In [13]:
import os
import numpy as np
from itertools import product
import sys

graph_problem = "MUTAG"
graph_folder = "../../perslay/tutorial/data/" + graph_problem + "/" # this should point to a perslay repository
sys.path.append(os.path.abspath(".."))

In [14]:
import atol
from sklearn.cluster import KMeans
from atol.atol import Atol


In [15]:
import numpy as np
from sklearn.cluster import KMeans

# Sample measures
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[1.1, 2.2], [3.3, 4.4], [5.5, 6.6]])
c = np.array([[-1, -2], [-3, -4], [-5, -6]])
X = [a, b, c]
y = [0, 0, 1]  # Labels for supervised learning

# Instantiate the Atol vectoriser with supervised learning enabled
atol_vectoriser = Atol(quantiser=KMeans(n_clusters=2), supervised=True)

# Fit the model and transform the data
atol_vectoriser.fit(X, y)
features = atol_vectoriser.transform(X)

print("Feature vectors:\n", features)

# Vectorize a single measure
single_feature = atol_vectoriser(a)
print("Feature vector for measure 'a':\n", single_feature)


Feature vectors:
 [[1.13168314 1.18588228 0.01199125 0.08597276]
 [1.07596094 1.0398231  0.01041078 0.07452165]
 [0.09467611 0.01325094 1.33308059 1.16216953]]
Feature vector for measure 'a':
 [1.13168314 1.18588228 0.01199125 0.08597276]
